server:
  port: 8014

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: SNG1







